- name: 'Build Gerrit AMI'
  hosts: localhost
  connection: local
  tasks:
  - include_role:
      name: alpha-deploy-lib/deploy-instance
    vars:
      settings: 
        VolumePath: /var/lib/gerrit
        ServiceAlias: gerrit
